### ISSUE TITLE
Some minor licensing request

### ISSUE THREAD

**Issue by jackytank** [NNBnh/flappybirdart#1]
Hey first of all excellent work of yours

Me and my team liked your design on flappy bird and planned to use it in our commercial website for proprietary purposes and we saw you had licensed it with CC0-1.0 license, as a matter of reassurance we want to confirm if we are permitted to utilize your open work on our project, thank you

**Comment by NNBnh** [comment]
Sure! Feel free to use it. 👍 👌

**Comment by NNBnh** [comment]
Oh but note that the purpose of this repo is to manage resources for my friend's homework. I do not own the birds sprites, those sprites were included in here just for convenience purpose. Other than that [every things else I show on the README.md](https://github.com/NNBnh/flappybirdart?tab=readme-ov-file#-about) are drawn by me and are free to use.

**Comment by jacqueschar** [comment]
Hi, we had noted and acknowledged your comment, thank you for informed us
